### ISSUE TITLE
I commented out two lines to get it work on Linux

### ISSUE THREAD

**Issue by AlManja** [CristiVlad25/steem-desktop#2]
These two lines were causing problems for me (Linux Manjaro, Python 3.6) and I had to comment them out, to get app working.

(13)   root.iconbitmap('stm.ico')
(22)   style.theme_use('winnative')

Let me know if there is any other information you need. Python beginner here

**Comment by CristiVlad25** [comment]
well, for starters, winnative is intuitively to be used in windows environments :)
second, I suspect the you may have not downloaded the .ico file in the same folder with the .pyw, or there may be a dependency issue for ico files in linux. 

thanks for pointing this out!
